INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Amaciante concentrado 500ml', '10.90', '1', '15');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Cerveja Lata 350ml', '2.65', '6', '2');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Refrigerante Guaranita 2L', '3.19', '7', '3');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Cerveja Lata 259ml', '1.80', '6', '4');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Arroz Tipo 1 5Kg', '12.56', '5', '1');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Cerveja Puro Malte Lata 350ml', '2.98', '6', '6');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Cereais Matinal Milho 500gr', '8.93', '5', '8');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Margarina c/ sal 500gr', '5.89', '8', '8');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Achocolatado em pó Nescau 2.0 500gr', '5,79', '4', '9');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Leite Tradicional 1L', '3.58', '8', '10');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Farinha de Trigo tipo 1 500gr', '4.96', '5', '11');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Sabão Detergente liquido 500ml', '3.15', '2', '12');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Suco Tang Laranja 35gr', '1.40', '7', '13');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Suco Tang Morango 35gr', '1.40', '7', '13');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Suco Tang Maracujá 35gr', '1.40', '7', '13');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Suco Tang Uva 35gr', '1.40', '7', '13');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Pão Francês Kg', '17.35', '13', '14');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Esponja de aço 500gr', '3.40', '2', '16');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Biscoito Cream Cracker 900gr', '4.80', '4', '17');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Pão de Forma 500gr', '3.50', '13', '18');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Biscoito Club Social Original 390gr', '8.04', '4', '19');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Biscoito Maizena 493gr', '4.50', '4', '20');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Maçã Gala Kg', '4.90', '12', '21');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Limão Kg', '2.03', '12', '21');
INSERT INTO `produto` (`idproduto`, `nome`, `valor`, `categoria_produto_idcategoria_produto`, `marca_idmarca`) VALUES (NULL, 'Banana Nanica Kg', '3.65', '12', '21');